### ISSUE TITLE
Sorting Git Repository 

### ISSUE THREAD

**Issue by im-Kitsch** [im-Kitsch/RMR_sensor_fusion#11]
@raultron 
we want to sort out our github resposity. Because the current version always  puzzles us and some file-tracking is very orderless. We fixed many times but it doesn't work well.  It wastes too much time to migrate the code.
Now we decide to sort out our project make it systematic. We plan to firstly clear the current resposity, Then divide the project to followed branches.  The current status of resposity is  really confused.  And we haven't efficiently used git these days.

--> Branch-Nucleo-Master 
    |--> Important Branch Nucleo 1
    |--> Important Branch Nucleo 2
  ..........
--> Branch-HLP-Master 
    |--> Important Branch HLP 1
    |--> ...........
--> Branch-Data.

Our project will be based on these three master branches. （When we make some staged progress we will create a new branch to save it, e.g. when we achiveve some partial functions like SPI, IIC.)
So that we can indenpently tracking the progress of different boards' code. And we just need one branch to wirte data. So we also create a new branch as data indenpendtly to save documents.

But the struct will be quite different to what you expected in the 1.st Issue. Maybe we should firstly ask your permission. It's not standard to manage the project but it's proper for us now. We still focus on main branch but just like divide master to three master branch. 

We have created the described branches and you can check it. If okay we will delete other useless branches and reserve a backup branch.

**Comment by malbreitenbach** [comment]
Just a little addition: The Nucleo project is working quite good on git. On the other hand we are struggling to use github effectivly for the HLP's project. We often get inexplicable build errors while working inside the git reposotory. We are also not able to store different projects of the HLP inside the 'src' folder because the projects folder name always needs to be called 'AscTec_SDK_v3.0'.

@im-Kitsch: I'm not sure if @raultron is able to understand all of your points, so possibly you should have a little talk about it on monday :)

Cheers!

**Comment by raultron** [comment]
Branches are the way to go. In essence, you create one folder for the HLP inside source named AscTec_SDK_v3.0 (which as you say will work) and then create branches every time you need to develop something new. Inexplicable build errors may happen because you are not using relative links in your project, everything should be relative to your base directory, also you have to properly use the .gitignore file so build files are not pushed into the repo.

You can have different developing branches for the HLP and the Nucleo, if they have different folders defined in src when you need to merge you won't have any conflicts.

**Comment by raultron** [comment]
Going back to your question, yes a reorganization is needed. For example, inside source you should only have two folders, one for the HLP and one for the Nucleo. Any intermediate test you can do it with branches.

**Comment by im-Kitsch** [comment]
@raultron SorryI have not exactly expressed the problem of SDK. The main problem of our IDE is that we can not import our modified project. We can only import from the orignial  xxxSDK.zip, which we download from website. We also test it, if firstly rightly import the project from the IDE, and then import the project to the IDE anyway, it doesn't work anyway, anyway we import. That problem we noted it in data, [SDK note](https://github.com/im-Kitsch/RMR_sensor_fusion/blob/master/data/tutorials/SDK%20Note.pdf). The IDE is specially modified by Eclipse, but bad and hard to use. ┭┮﹏┭┮.  This problem brings many chain problem. Like this, the IDE will automatically be created in the workspace, so the workspace has to be in git reposity. Like this, many useless setting files you have to test, if you can gitignore it. Like this, you can not directly copy to other, download from github,,,you can only replace your code to the raw project, which is imported from Asctec's original XXX.zip. It's a nightmare. (The products give us really so many nitghmares ┭┮﹏┭┮ 😢 ).

Also we have some problem in .gitignore before, you can see our so frequently commit about this file. But now it works okay. Surely we should first good initialize gitignore before porject beginning. Maybe the later people can refine our .ignore.

Go back to the problem, I highly agree to you that the branches is to go, is to merge. But some branches should live not very short.  So there will be also some chain problem. 
For example, if I create a branch to do some changes about Nucleo, but while merging it also faces conflicts about HLP, which is unchanged in Nucleo but changed in Nucleo. 
Also for example, like I'm testing the read data about PX4Flow in Nucleo, but it will not be merged to Nucleo and it should be saved after it successes. And this case is not orphan case.

That's why I highly stand by using two branches to avoid coupling. ┭┮﹏┭┮

**Comment by raultron** [comment]
Merging won't produce conflicts if you don't change the same files. If you are working in HLP and the others are working on Nucleo the merge won't have conflicts. Maybe you are changing all the files in your local copy at your PC and that is why it creates a merge conflict for other folders and files as well. The whole concepts of branches is precisely this rapid development of new features. You can create one branch for each feature if you want and merged them into the main branch as they are finished. 

The problem with IDE should be possible to solve, Eclipse is also designed to work with code versioning so everything should be relative to the main directory, it may be that you are missing some important configuration in Eclipse.
