### ISSUE TITLE
Protocol improvements

### ISSUE THREAD

**Issue by malbreitenbach** [im-Kitsch/RMR_sensor_fusion#13]
Hello @raultron, hello @Dino,
As you saw in  #10 we need to increase the protocol's performance. One way is to try the DMA on the Nucleo, but to be honest I don't have any experience in DMA. I'm also not sure if this would increase the performance by far, because the measured performance (330Hz) is not limited by the Nucleo but mostly by the HLP (which does not support DMA) at this point.

I was thinking about two different protocol implementations instead:
## 1st Option
<code>

|HLP|Nucleo|
| --- | --- |
|Read Sensory| Wait for Handshake  |
|Performing Handshake|Performing Handshake|
|Send Sensory data|Receive Sensory data|
|Wait for Handshake|Perform SensorFusion / Control algorithm|
|Performing Handshake|Performing Handshake|
|Receive Control data|Send Control data|
|Use Control data|Wait for Handshake|
|Read Sensory| Wait for Handshake  |
|[...]| [...]  |
</code>

## 2nd Option
<code>

|HLP|Nucleo|
| --- | --- |
|[...]| [...]  |
|Performing Handshake|Performing Handshake|
|Send new Sensory data / Receive last Control data|Send Control data/Receive Sensory data|
|Read Sensory / Use Control data |Perform SensorFusion / Control algorithm|
|Performing Handshake|Performing Handshake|
|Send new Sensory data / Receive last Control data|Send Control data/Receive Sensory data|
|Read Sensory / Use Control data |Perform SensorFusion / Control algorithm|
|[...]| [...]  |
</code>

While the 1st option is not using the duplex functionality, the second option is. There is a classic tradeoff between throughput and latency. The first option has the minimal latency, because the Nucleo is waiting for the sensory data, then performing the SensorFusion immediately and is sending back the calculated control signals right after that. 
On the other hand the second option allows a higher throughput, because while the HLP is already reading the new sensory data (from the sensors) the Nucleo is performing the SensorFusion on the "old" sensory data. But if the "Sensor Fusion"-duration is shorter than the "Sensory Reading"-duration the latency will be increased.

Edit: I'm not sure, if the tables are showing the idea clearly enough. If not, I will add some graphics.

**Comment by raultron** [comment]
Completely clear, I'll have to sit and discuss it with Dinu though, we will get back at you.

**Comment by im-Kitsch** [comment]
Very agree that DMA can not speed up it. @malbreitenbach And I stand by option 2.

And but theoretically I have a question. By the handshake, HLP can not wait for handshake using while loop until handshake finished. We can only every loop take time to try handshake and after a "timeout" give up handshake when the request is not responsed. Seems like that the handshake takes time. 

How do you think if we test dropping handshake? For that handshake is to show ready for transmitting. My opinion is that the problem comes from that only Master(HLP) decide send and receive. If Nucleo can also initiative send data, it will be easier. 
My idea to Nucleo to replace this problem like this:

We use SPI Receive interrupt in Nucleo to receive data.  Main loop only do sensorfusion. If sensorfusion has been calculated for this iteration, the special Flag will be set. 

HLP | Nucleo
----|----
 SPI_TransmitReceive() | 
Receive Data/Information | Interrupt is activated.->  <br>Check the special Flag-> <br>if is set, transmit calculated package -> <br>if not, transmit information that calculating not finished.
Next loop |  Next Loop

Firstly, I'm not sure if it's proper for the calculating, because it bases on some assumption such like that the calculating of sensorfusion is not "so delayed".
Secondly, I think we can simply test if we remove handshake, see if obviously more packages can be transmitted per second, ignoring success rate. And another test, adding many calculation in mainloop, like i-- or random--, see if the transmitting will be delayed.  If these two tests true, maybe we can have look of interupt. If not, we stay polling.

**Comment by malbreitenbach** [comment]
Thanks for the replys!  

@im-Kitsch 
`By the handshake, HLP can not wait for handshake using while loop until handshake finished.`

I'm not quite sure, what you mean by that.
But I agree that an interrupt based SPI could increase the overall performance. I'm suspending the handshake to be time expencive as well. I don't think that it would be helpful to interrupt the sensor fusion by the way, because a subprogram call is always taking some time (store/restore registers, etc...), so this may increase the latency. Tomorrow I will do some code profiling so we will see how long the handshake really takes, this will defenetly help to decide. I will also try your testing methods you mentioned at the end. 
Results are following tomorrow on this place 👍

**Comment by im-Kitsch** [comment]
@malbreitenbach Sorry I have not described it clearly. I mean that if HLP want to communicate with Nucleo, it will firstly make handshake to Nucleo. But we use the while loop to wait successful handshake. The program in HLP will always do SPI handshake until successful handshake. Sometimes it may be endless loop or long time loop. So we need a timeout, it behave as a threshold of handshake.

It's just like some libraries function in HAL, like communication of UART, SPI, I2C. ->,
XXXsendData( xx, *data, xx, xx, xx, timeout  ) != HAL_OK -> like this timeout.

And a small addition, my idea about protocol also comes from we using these interfaces to read data from peripherals like memories. 
XXsendData( para xx, para xx, DevAddress xx, *ptr xx, timeout xx);
XXReceiveData( para xx, para xx, DevAddress xx, *ptr xx, timeout xx)
  
And have a good time tomorrow!
Cheers!

**Comment by malbreitenbach** [comment]
Today I tried some code profiling. It worked for a short time but I think my debugger is broken or at least not working correctly. I will have an other try tomorrow. 
What I successfully found out was the proportion of the handshake in the whole transfer: 
The handshake only takes 3% of the hole transfer time, so I think thats okay for now.

Hopefully more results tomorrow.

**Comment by malbreitenbach** [comment]
@raultron @Dinu
Yesterday we found out that the begugger is decreasing the real performance to ~45%. So running our protocol without the debugger leads to a performance of 750Hz (package size: 80 Bytes). Means we send 750 packets (each 80 Bytes) per second.

**Comment by malbreitenbach** [comment]
@raultron @Dinu
Today we found out that there is an other performance factor. When we connect the remote to the Firefly, the performance is increased by far.

A small illustration:

<code>

| Environmental conditions  | Performance (messages per minute) |
| ------------- | ------------- |
| Debugger activated & Remote turned off  | 21.000 |
| Debugger deactivated & Remote turned on  | 58.000  |

</code>

Info: Nucleo's SPI interrupt-based and buffered,  HLP's SPI in blocking mode.

Have a nice day!

**Comment by malbreitenbach** [comment]
See #11 for the current state.
