### ISSUE TITLE
Accuracy of the timestamp (Low Priority Issue)

### ISSUE THREAD

**Issue by malbreitenbach** [im-Kitsch/RMR_sensor_fusion#18]
We added a timestamp to our protocol message for testing reasons. This timestamp shows when the message was created. Therefore it is an indicator how much time it needs for one  message to 

1. build the message (later: sensory data)
2. sent to the Nucleo
3. process on the nucleo (build a reply message depending on the received data) / build reply message (later: control data)
4. sent reply message back to the HLP
5. reconstruct reply message 

For reference a timer value is used. The Timer is of cause configurable, so we can decide about the accurancy. At the moment we are transmitting messages at 500 - 1000Hz (meaning there is one message every 1ms - 2ms). 
@raultron @Dinu Any assessments about a valid accurancy?

- Higher Accurancy (faster count) -> More Overflows / bigger counter range needed (more Bytes to transmit per message)

- Lower Accurancy (slower count) -> Less Overflows / smaller counter range needed (less Bytes to transmit per message)

**Comment by raultron** [comment]
Hi,

Take a look into Mavlink ( a protocol for UAV communications), we don't use it because it is overkill for what we want but you can learn something from that protocol: http://mavlink.org/messages/common

What I understand is that they have some big variables (uint64) for storing the time inside the microcontroller with microsecond accuracy, the timer is counted from the moment the microcontroller is booted.

Then for each kind of message depending on the type of information and the rate they decide to send the timestamp either in seconds, milliseconds or microseconds or all. You can also see the size of the variables that they are using. I think a 64bit variable to store time in microseconds is reasonable and will give you plenty of counting range to keep the device ON for days.

**Comment by malbreitenbach** [comment]
Hey @raultron,
thanks for the reply! The timer on the HLP has a 32 - bit counter register,  so we will have to count the overruns to generate a fictional 64bit counter. With your approval I will build the 1microSecond based 64-bit "timestamp generator".

PS: A tutorial is created soon how to repair the bootloader on the HLP :)
